CATEGORY_KEYWORDS: dict[str, list[str]] = {
    "frutas": [
        "banana",
        "maca",
        "maçã",
        "pera",
        "laranja",
        "uva",
        "melao",
        "melão",
        "morango",
        "fruta",
    ],
    "legumes": [
        "tomate",
        "cebola",
        "cenoura",
        "alface",
        "pepino",
        "courgette",
        "brocolo",
        "brócolo",
        "batata",
        "legumes",
    ],
    "especialidades": [
        "especialidade",
        "frescos",
    ],
    "quarta gama": [
        "salada",
        "mistura",
        "sopa",
        "pronta a consumir",
        "quarta gama",
    ],
    "cogumelos": [
        "cogumelo",
        "cogumelos",
        "champignon",
        "marron",
    ],
    "frutos secos e desidratados": [
        "amendoa",
        "amêndoa",
        "noz",
        "caju",
        "pistacio",
        "pistácio",
        "desidratado",
        "uva passa",
    ],
    "azeitonas e tremocos": [
        "azeitona",
        "azeitonas",
        "tremoco",
        "tremoço",
        "tremocos",
        "tremoços",
    ],
}
